### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/jester/annotations/jester-v1-labels.csv'

### ISSUE THREAD

**Issue by Yiiiiiiiiii** [sli057/Geo-TRAP#1]
excuse me!  I want to know how to download the "jester " datasets  and ti's (annotations) file   ?????     thank you!!!

**Comment by sli057** [comment]
Hi,
I found the "jester" dataset website was closed, but you can still get it in the new website, https://developer.qualcomm.com/software/ai-datasets/jester.
